### ISSUE TITLE
Add argument for numDeriv::grad() method

### ISSUE THREAD

**Issue by BodoBurger** [compstat-lmu/ame#8]

**Comment by giuseppec** [comment]
I think `computeAME(other.args, method = "simple")` should already work as I am passing this down to `
derivative(other.args, method = "simple")` with the `...` arg.

https://github.com/compstat-lmu/ame/blob/aa2b6df252fecf2fa952cf09f550cf7e51166b98/R/derivative.R#L29

**Comment by BodoBurger** [comment]
Yes, it works.

Ok, then no other argument should be called "method". ;)

And I will document it.
